name: JSON functions
on: push
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${CONTEXT}"
        env:
          CONTEXT: ${{ toJSON(github) }} # githubコンテキストをJSON文字列でダンプ
      - run: echo "${JOB}"
        env:
          JOB: ${{ toJSON(job) }} # jobコンテキストをJSON文字列でダンプ
      - run: echo "${ENV}"
        env:
          ENV: ${{ toJSON(env) }} # envコンテキストをJSON文字列でダンプ
